apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: apisix
type: Opaque
stringData:
  password: "p@ssw0rd"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: apisix
spec:
  clusterIP: None
  selector:
    app: apisix-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apisix-redis
  namespace: apisix
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: apisix-redis
  template:
    metadata:
      labels:
        app: apisix-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password
          command:
            - sh
            - -c
            - |
              redis-server \
                --requirepass "$REDIS_PASSWORD" \
                --appendonly yes \
                --appendfsync everysec \
                --dir /data
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi